package com.shoppingCart.ShoppingCart.dto;

import com.fasterxml.jackson.annotation.JsonBackReference;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import java.util.Date;

@AllArgsConstructor
@RequiredArgsConstructor
@Setter
@Getter
public class PaymentResponse {
    // Autogenerated ID for the payment. Not necessary to provide.
    @Schema(name = "idPayment", required = false, example = "1", defaultValue = "2", description = "This key is autogenerated, it's not necessary")
    private Integer idPayment;

    // Order associated with the payment. Must be provided and cannot be null.
    @Schema(name = "idOrder", required = true, example = "1", defaultValue = "2", description = "This key indicates the ID of the associated order")
    @JsonBackReference
    private OrderResponse idOrder;

    // Type of payment (e.g., cash, credit card). Must be provided.
    @Schema(name = "paymentType", required = true, example = "cash", defaultValue = "cash", description = "This key indicates the payment type")
    private String paymentType;

    // Status of the payment (e.g., pending, completed). Must be provided.
    @Schema(name = "status", required = true, example = "pending", defaultValue = "pending", description = "This key indicates the status of the payment")
    private String status;

    // Date when the payment was created.
    @Schema(name = "creatDate", required = true, example = "", defaultValue = "", description = "This key indicates payment creation date")
    private Date creatDate;

    // Date when the payment was last updated.
    @Schema(name = "updateDate", required = true, example = "", defaultValue = "", description = "This key indicates payment update date")
    private Date updateDate;
}
