package com.shoppingCart.ShoppingCart.dto;

import com.fasterxml.jackson.annotation.JsonBackReference;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@RequiredArgsConstructor
@Setter
@Getter
public class PaymentRequest {
    // The ID of the payment. This field is autogenerated and not necessary to provide.
    @Schema(name = "idPayment", required = false, example = "1", defaultValue = "2", description = "This key is autogenerated, it's not necessary")
    private Integer idPayment;

    // The associated order ID. This field is required.
    @Schema(name = "idOrder", required = true, example = "1", defaultValue = "2", description = "This key is to indicate the id order")
    @NotNull
    @JsonBackReference
    private OrderResponse idOrder;

    // The type of payment. This field is required and cannot be blank.
    @Schema(name = "paymentType", required = true, example = "cash", defaultValue = "cash", description = "This key is to indicate the payment type")
    @NotBlank
    private String paymentType;

    // The status of the payment. This field is required and cannot be blank.
    @Schema(name = "status", required = true, example = "pending", defaultValue = "pending", description = "This key indicates the status of the payment")
    @NotBlank
    private String status;
}
